OrdererOrgs:
  - Name: Orderer
    Domain: wangchen.com
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: bg_org1
    Domain: org1.wangchen.com
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: bg_org2
    Domain: org2.wangchen.com
    EnableNodeOUs: false
    Template:
      Count: 2
    Users:
      Count: 1
