# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'  

services:
  z0:
    container_name: z0
    extends:
      file: base/zookeeper-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=z0:2888:3888 server.2=z1:2888:3888 server.3=z2:2888:3888
  z1:
    container_name: z1
    extends:
      file: base/zookeeper-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=z0:2888:3888 server.2=z1:2888:3888 server.3=z2:2888:3888
    depends_on:
      - z0
  z2:
    container_name: z2
    extends:
      file: base/zookeeper-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=z0:2888:3888 server.2=z1:2888:3888 server.3=z2:2888:3888
    depends_on:
      - z1
  k0:
    container_name: k0
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=z0:2181,z1:2181,z2:2181
    depends_on:
      - z0
      - z1
      - z2
  k1:
    container_name: k1
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=z0:2181,z1:2181,z2:2181
    depends_on:
      - k0
  k2:
    container_name: k2
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=z0:2181,z1:2181,z2:2181
    depends_on:
      - k1
  kafka-manager:
    container_name: kafka-manager
    extends:
      file: base/kafka-base.yaml
      service: kafka-manager
    environment:
      ZK_HOSTS: "z0:2181,z1:2181,z2:2181"
    ports:
      - 9000:9000
    depends_on:
      - k2 
    
  orderer1.wangchen.com:
    container_name: orderer1.wangchen.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
    extends:
      file: base/orderer-base.yaml
      service: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/wangchen.com/orderers/orderer1.wangchen.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/wangchen.com/orderers/orderer1.wangchen.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    depends_on:
      - kafka-manager
  orderer2.wangchen.com:
    container_name: orderer2.wangchen.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
    extends:
      file: base/orderer-base.yaml
      service: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/wangchen.com/orderers/orderer2.wangchen.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/wangchen.com/orderers/orderer2.wangchen.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 8050:7050
    depends_on:
      - orderer1.wangchen.com
  peer0.org1.wangchen.com:
    container_name: peer0.org1.wangchen.com
    environment:
      - CORE_PEER_ID=peer0.org1.wangchen.com
      - CORE_PEER_LOCALMSPID=bgOrg1Msp
      - CORE_PEER_ADDRESS=peer0.org1.wangchen.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.wangchen.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.wangchen.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.wangchen.com:7051
    extends:
      file: base/peer-base.yaml
      service: peer
    volumes:
      - ./crypto-config/peerOrganizations/org1.wangchen.com/peers/peer0.org1.wangchen.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.wangchen.com/peers/peer0.org1.wangchen.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    depends_on:    
      - orderer2.wangchen.com      
      
  peer1.org1.wangchen.com:
    container_name: peer1.org1.wangchen.com
    environment:
      - CORE_PEER_ID=peer1.org1.wangchen.com
      - CORE_PEER_LOCALMSPID=bgOrg1Msp
      - CORE_PEER_ADDRESS=peer1.org1.wangchen.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.wangchen.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.wangchen.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.wangchen.com:7051
    extends:
      file: base/peer-base.yaml
      service: peer
    volumes:
      - ./crypto-config/peerOrganizations/org1.wangchen.com/peers/peer1.org1.wangchen.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.wangchen.com/peers/peer1.org1.wangchen.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053
    depends_on:
      - peer0.org1.wangchen.com
  peer0.org2.wangchen.com:
    container_name: peer0.org2.wangchen.com
    environment:
      - CORE_PEER_ID=peer0.org2.wangchen.com
      - CORE_PEER_LOCALMSPID=bgOrg2Msp
      - CORE_PEER_ADDRESS=peer0.org2.wangchen.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.wangchen.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.wangchen.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.wangchen.com:7051
    extends:
      file: base/peer-base.yaml
      service: peer
    volumes:
      - ./crypto-config/peerOrganizations/org2.wangchen.com/peers/peer0.org2.wangchen.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.wangchen.com/peers/peer0.org2.wangchen.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11052:7052
      - 11053:7053
    depends_on:
      - peer1.org1.wangchen.com     
  peer1.org2.wangchen.com:
    container_name: peer1.org2.wangchen.com
    environment:
      - CORE_PEER_ID=peer1.org2.wangchen.com
      - CORE_PEER_LOCALMSPID=bgOrg2Msp
      - CORE_PEER_ADDRESS=peer1.org2.wangchen.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.wangchen.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.wangchen.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.wangchen.com:7051
    extends:
      file: base/peer-base.yaml
      service: peer
    volumes:
      - ./crypto-config/peerOrganizations/org2.wangchen.com/peers/peer1.org2.wangchen.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.wangchen.com/peers/peer1.org2.wangchen.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12052:7052
      - 12053:7053
    depends_on:
      - peer0.org2.wangchen.com
  ca0:
    container_name: ca_peerOrg1
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-peerOrg1
    extends:
      file: base/ca-base.yaml
      service: ca
    ports:
      - 7054:7054
    volumes:
      - ./crypto-config/peerOrganizations/org1.wangchen.com/tlsca/tlsca.org1.wangchen.com-cert.pem:/etc/hyperledger/fabric-ca-server-config/tls/cert.pem
      - ./crypto-config/peerOrganizations/org1.wangchen.com/tlsca/46a5194bfc894a1806ca2d6e65c2131c1b52b13f2613b9c704c19f359d6fa9ff_sk:/etc/hyperledger/fabric-ca-server-config/tls/keyfile_sk
      - ./crypto-config/peerOrganizations/org1.wangchen.com/ca/ca.org1.wangchen.com-cert.pem:/etc/hyperledger/fabric-ca-server-config/ca/cert.pem
      - ./crypto-config/peerOrganizations/org1.wangchen.com/ca/85cf4251f546bfce20557a2a1634d64dd97cc2ed3bc1e870b709b8be2dcf6e28_sk:/etc/hyperledger/fabric-ca-server-config/ca/keyfile_sk
    depends_on:
      - peer1.org2.wangchen.com
  ca1:
    container_name: ca_peerOrg2
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-peerOrg2
    extends:
      file: base/ca-base.yaml
      service: ca
    ports:
      - 8054:7054
    volumes:
      - ./crypto-config/peerOrganizations/org2.wangchen.com/tlsca/tlsca.org2.wangchen.com-cert.pem:/etc/hyperledger/fabric-ca-server-config/tls/cert.pem
      - ./crypto-config/peerOrganizations/org2.wangchen.com/tlsca/5161e8f8e92bb7433bc838a129535cf08957f590c884bba74172f5c2fae5d719_sk:/etc/hyperledger/fabric-ca-server-config/tls/keyfile_sk
      - ./crypto-config/peerOrganizations/org2.wangchen.com/ca/ca.org2.wangchen.com-cert.pem:/etc/hyperledger/fabric-ca-server-config/ca/cert.pem
      - ./crypto-config/peerOrganizations/org2.wangchen.com/ca/a60e8e585fa4fb0ac6d671079507ce7f37032b4a75ced8ea12178bd04f7f935d_sk:/etc/hyperledger/fabric-ca-server-config/ca/keyfile_sk
    depends_on:
      - ca0
  # fabric-edge:
    # container_name: fabric-edge
    # environment:
      # - USERNAME=wangchen
      # - PASSWORD=password
      # - MYSQL_DATA_SOURCE_URL=jdbc:mysql://fabric-db:3306/fns?serverTimezone=UTC&useSSL=false
      # - MYSQL_DATA_SOURCE_USERNAME=root
      # - MYSQL_DATA_SOURCE_PASSWORD=123456
    # extends:
      # file: base/edge-base.yaml
      # service: edge
    # ports:
      # - 8080:8080
    # depends_on:
      # - fabric-db
  # fabric-db:
    # container_name: fabric-db
    # privileged: true
    # extends:
      # file: base/edge-base.yaml
      # service: mysql
    # environment:
      # - MYSQL_ROOT_PASSWORD=123456
    # volumes:
      # - ./edge/logs:/logs
      # - ./edge/data:/var/lib/mysql
      # - ./edge/conf:/etc/mysql/conf.d
      # - ./edge/init:/docker-entrypoint-initdb.d
    # depends_on:
      # - ca1
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.org1.wangchen.com:7051
      - CORE_PEER_LOCALMSPID=bgOrg1Msp
      - CORE_PEER_LOCALMSPTYPE=bccsp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wangchen.com/peers/peer1.org1.wangchen.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wangchen.com/peers/peer1.org1.wangchen.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wangchen.com/peers/peer1.org1.wangchen.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wangchen.com/users/Admin@org1.wangchen.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 20; chmod u+x ./scripts/script.sh; ./scripts/script.sh $CHANNEL_NAME $TLS_ENABLED; sleep $TIMEOUT'
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
    depends_on:
      - ca1
  