# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
    kafka:
        image: hyperledger/fabric-kafka
        restart: always
        environment:
          - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
          - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
          - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
        ports:
          - "9092"
    kafka_manager:
        image: hlebalbau/kafka-manager:latest
        environment:
            APPLICATION_SECRET: "random-secret"
        command: -Dpidfile.path=/dev/null